<div class="actions dropdown chaos-dropdown">
    <span class="action toggle" data-mage-init='{"dropdown":{}}' data-toggle="dropdown" aria-haspopup="true">
        Dropdown
    <span>span + dropdown</span>
    </span>
    <ul class="dropdown">
        <li>
            <span class="item">PHP</span>
        </li>
        <li>
            <span class="item">Magento 2</span>
        </li>
        <li>
            <span class="item">CMS</span>
        </li>
    </ul>
</div>