<?php
$viewModelFileList = $block->getData('view_model_filelist');
$viewModelClassInformant = $block->getData('view_model_classinformant');
$viewModelDependencyInjection = $block->getData('view_model_dependencyinjection');
$path = 'app/code';
$publicMethods = $viewModelClassInformant->getPublicMethods($this);
$classConstants = $viewModelClassInformant->getConstants($block);
$fileList = $viewModelFileList->getFileList($path);
$diProperties = $viewModelDependencyInjection->getArguments();
?>
    <section class="class-informant">
        <h3 class="section-header">Show $this public methods</h3>
        <?php if (isset($publicMethods)) : ?>
            <dl class="methods-list">
                <?php foreach ($publicMethods as $publicMethod => $data) : ?>
                    <div>
                        <dt class="class-name">Class name: </dt>
                        <dd><?= $data['class']; ?></dd>
                        <dt>Method name:</dt>
                        <dd><?= $data['name']; ?></dd>
                    </div>
                <?php endforeach; ?>
            </dl>
        <?php endif;?>

        <h3 class="section-header">Show $block constants</h3>
        <?php if (isset($classConstants)) : ?>
            <dl class="constants-list">
                <?php foreach ($classConstants as $class => $data) : ?>
                    <dt class="class-name">Class name: </dt>
                    <dd>
                        <p><?= $class; ?></p>
                        <dl>
                            <?php foreach ($data as $dataKey => $dataValue) : ?>
                                <dt><?= $dataKey; ?></dt>
                                <dd><?= $dataValue; ?></dd>
                            <?php endforeach; ?>
                        </dl>
                    </dd>
                <?php endforeach; ?>
            </dl>
        <?php endif;?>
    </section>
    <section class="file-list">
        <h3 class="section-header">Show files in <?= $path; ?></h3>
        <?php if (isset($fileList)) : ?>
            <ul class="reset-list">
                <?php foreach ($fileList as $fileItem => $fileData) : ?>
                    <li>
                        <p>
                            <span class="file-name">File/Dir name: <?= $fileItem; ?></span>
                            <span class="file-data">Location: <?= $fileData['path']; ?></span>
                            <span class="file-data">Created/modified at: <?= $fileData['created/modified']; ?></span>
                        </p>
                    </li>
                <?php endforeach; ?>
            </ul>
        <?php endif; ?>
    </section>

<?php if (isset($diProperties)) : ?>
    <section class="dependency-injection">
        <h3 class="section-header">Show Object constructor arguments</h3>
        <ul class="reset-list">
            <?php foreach ($diProperties as $propertyName => $propertyValue) :
                if ($propertyValue === null) {
                    $propertyValue = 'null';
                }
                if (is_array($propertyValue)) {
                    $propertyValue = $propertyValue['instance'] ?? 'array';
                }?>
                <li>
                    <p>Argument name: <?= $propertyName; ?></p>
                    <p>Property value: <?= $propertyValue; ?></p>
                </li>
            <?php endforeach; ?>
        </ul>
    </section>
<?php endif; ?>